In [2]:
import numpy as np

# Date 27-04-2022

In [4]:
# Create one dimensional array 

In [5]:
data = [4,5,6,7]
a = np.array(data)
a

array([4, 5, 6, 7])

In [6]:
a.ndim #this will tell us wheather a is one or 2 D array

1

In [7]:
print(a.size)

4


In [8]:
# element-wise operations

In [9]:
a*3 #all the elements in the array will be multiplied by 3 without changing the actual original array

array([12, 15, 18, 21])

In [10]:
b= a**2 #all the elements in array will be powered by 2 without making changes to the actual array
print(b)

[16 25 36 49]


In [11]:
# checking if a is unchanged or not
a

array([4, 5, 6, 7])

In [12]:
#hence we can see the elements in the array a is unchanged

In [13]:
# Indexing and slicing

In [14]:
#indexing
a[-1] #right to left indexing negative indexing

7

In [15]:
a[-2]

6

In [16]:
a[2] #left to right indexing positive indexing

6

In [17]:
a[1]

5

In [18]:
# Slicing
a[1:3] #start, stop

array([5, 6])

In [19]:
#Remeber the output of the stop point will not be included in the output

In [20]:
#Two dimensional array

In [21]:
d = [[1,2,3],[4,5,6],[7,8,9]]
d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
s= np.array(d)
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
s.ndim # telling the user the dimensions of the array

2

In [24]:
s.shape

(3, 3)

In [25]:
s.size

9

In [26]:
#indexing and slicing

In [27]:
#indexing
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
s[-1,-2] #using the negative indexing to locate an element

8

In [29]:
s[1,2] #using positive indexing to locate the element in the array

6

In [30]:
#print the entire row of a 2 dimensional array
s[1] #using positive indexing

array([4, 5, 6])

In [31]:
s[-1] #using negative indexing

array([7, 8, 9])

In [32]:
#slicing
s[:,0] #This how you can get the first column of all the rows in a 2D array

array([1, 4, 7])

In [33]:
s[:2,1:]

array([[2, 3],
       [5, 6]])

In [34]:
s[1:,:2]

array([[4, 5],
       [7, 8]])

In [35]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
s[:,1:] #s[starting row : ending row , starting column : ending column]
#Note the ending element entered will not be included in the output

array([[2, 3],
       [5, 6],
       [8, 9]])

# Date 28-04-2022

## arange

In [37]:
#arange()
#It is another way of creating a 1D array

In [38]:
d = np.arange(0,9) #start,stop,step
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
#Reshape an array

In [40]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
k = d.reshape(3,3)  #possible rehape arrays (3,3) , (9,1) , (1,9)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
j = s [:,1:3]
j

array([[2, 3],
       [5, 6],
       [8, 9]])

In [43]:
m = j.reshape(2,3)
m

array([[2, 3, 5],
       [6, 8, 9]])

## Array concatination

In [44]:
x = np.array([[2,3],[4,5]])
y = np.array([[1,8],[7,9]])

In [45]:
x

array([[2, 3],
       [4, 5]])

In [46]:
y

array([[1, 8],
       [7, 9]])

In [57]:
f = np.concatenate((x,y),axis=1) #columnwise concatination
f

array([[2, 3, 1, 8],
       [4, 5, 7, 9]])

In [58]:
u = np.concatenate((x,y),axis=0) #rowise concatenation
u

array([[2, 3],
       [4, 5],
       [1, 8],
       [7, 9]])

## Transpose of the array

In [52]:
f.transpose()

array([[2, 4],
       [3, 5],
       [1, 7],
       [8, 9]])

In [54]:
f

array([[2, 3, 1, 8],
       [4, 5, 7, 9]])

In [55]:
u.transpose()

array([[2, 4, 1, 7],
       [3, 5, 8, 9]])

In [56]:
u

array([[2, 3],
       [4, 5],
       [1, 8],
       [7, 9]])

## matrix multiplication

In [62]:
x

array([[2, 3],
       [4, 5]])

In [63]:
y

array([[1, 8],
       [7, 9]])

In [66]:
c = np.matmul(x,y) #matrix multiplication

In [67]:
c

array([[23, 43],
       [39, 77]])

In [68]:
f

array([[2, 3, 1, 8],
       [4, 5, 7, 9]])

In [69]:
u

array([[2, 3],
       [4, 5],
       [1, 8],
       [7, 9]])

In [73]:
v = np.matmul(f,u) #matrix multiplication

In [74]:
v

array([[ 73, 101],
       [ 98, 174]])

In [75]:
#x-->(2,3) # column of x is not equal to row of y matrix so matrix multiplication is not possible
#y-->(4,3)

#transpose y to solve this problem
#x-->(2,3) #not matrix multiplication is possible
#y-->(3,4)

## unique values

In [76]:
z=np.array([0,2,1,2,0,3,4,4,3,4])

In [78]:
np.unique(z,return_counts = True) #This will show the number of times an element is repeated in the array

(array([0, 1, 2, 3, 4]), array([2, 1, 2, 2, 3]))

## Change the nD array into 1D array

In [79]:
f

array([[2, 3, 1, 8],
       [4, 5, 7, 9]])

In [81]:
e = f.flatten()
e

array([2, 3, 1, 8, 4, 5, 7, 9])

## finding out the elements greater than 5 in array

In [82]:
e

array([2, 3, 1, 8, 4, 5, 7, 9])

In [84]:
e[e>5] #this will return the values in array which are greater than 5

array([8, 7, 9])

In [86]:
f[f<3]  #this will return the values in array which are less than 5=3

array([2, 1])

In [90]:
## getting the indexes of the values greater than 5
indexes = np.where(f>4) #f is a 2D array
indexes

(array([0, 1, 1, 1]), array([3, 1, 2, 3]))

In [91]:
indexes = np.where(e>4) #e is a 1D array
indexes

(array([3, 5, 6, 7]),)

## Adding arrays vertically

In [92]:
 x

array([[2, 3],
       [4, 5]])

In [93]:
y

array([[1, 8],
       [7, 9]])

In [95]:
np.vstack((x,y))

array([[2, 3],
       [4, 5],
       [1, 8],
       [7, 9]])

In [96]:
np.hstack((x,y))

array([[2, 3, 1, 8],
       [4, 5, 7, 9]])

## How to find mean and median in array

In [101]:
z

array([0, 2, 1, 2, 0, 3, 4, 4, 3, 4])

In [102]:
np.mean(z) #finding mean in array z

2.3

In [103]:
np.median(z) #finding median in array z

2.5

## how to generate randome values in nD array

In [118]:
np.random.randint(1,10,(3,4)) #generating random number in integer form # argument start,stop, shape

array([[1, 1, 3, 2],
       [4, 5, 6, 7],
       [3, 8, 6, 6]])

In [121]:
np.random.uniform(-1,1,(3,4)) 
#it generates random float values in between a particular range #-1 = starting,1 = ending,(3,4) = shape of the matrix

array([[ 0.42931818,  0.0588659 , -0.80562508,  0.65595092],
       [-0.80192687, -0.57579279, -0.1832773 ,  0.16562306],
       [ 0.58452002, -0.92910208,  0.7729386 , -0.45525804]])

In [108]:
np.random.rand(2,3) #this will generate randome values in float between 1 and 0

array([[0.33669467, 0.11321821, 0.40383047],
       [0.81736227, 0.01445906, 0.38221015]])

In [111]:
m = np.linspace(0,1,50) # 0= start, 1= stop, 50 = number of element

In [124]:
np.random.shuffle(m) #it shuffles the values inside the array and automatically stores in the array
m

array([0.10204082, 0.30612245, 0.69387755, 0.02040816, 0.14285714,
       0.08163265, 0.89795918, 0.06122449, 0.95918367, 0.57142857,
       0.6122449 , 0.16326531, 0.42857143, 0.3877551 , 0.51020408,
       0.12244898, 0.75510204, 0.34693878, 0.40816327, 0.04081633,
       0.44897959, 0.32653061, 0.59183673, 0.28571429, 0.65306122,
       0.73469388, 0.        , 0.93877551, 0.67346939, 0.24489796,
       0.87755102, 0.55102041, 0.71428571, 0.79591837, 0.53061224,
       1.        , 0.91836735, 0.63265306, 0.81632653, 0.36734694,
       0.18367347, 0.46938776, 0.97959184, 0.85714286, 0.48979592,
       0.2244898 , 0.7755102 , 0.26530612, 0.83673469, 0.20408163])

In [125]:
m.max() #it returns max value

1.0

In [126]:
m.min() #it returns max value

0.0

In [127]:
m.argmin() #it returns indexes of the minimum value

26

In [128]:
m.argmax() #it returns indexes of the maximum value

35