# KNN K nearest neighbours

## Steps followed by KNN

## Set the value of k . for example k=3 

## K's value will depend on number of classes 
## If no of classes is even then k will be odd
## If no of classes is odd then k will be even

In [19]:
from sklearn.datasets import load_iris

In [20]:
import pandas as pd

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
iris = load_iris()

In [23]:
x = iris.data

In [24]:
y = iris.target

In [25]:
print(x.shape)

(150, 4)


## Split data in train and test dataset

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.2,random_state=13)

## Initializing KNN class with euclidean equation metric with n_neighbors(k) = 3

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
knn = KNeighborsClassifier(metric = 'euclidean',n_neighbors = 3)

## Train KNN model

In [30]:
knn.fit(xtrain,ytrain) 

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

## Run prediction on Trained KNN model

In [31]:
pred = knn.predict(xtest)

In [32]:
pred

array([1, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 1, 1, 0, 2, 0, 2, 2, 1, 0, 1, 0,
       0, 2, 1, 2, 0, 2, 1, 2])

## Testing accuracy of the Trained KNN model

In [37]:
accuracy_score(ytest,pred) #accuracy of the KNN model on test dataset

0.9666666666666667

# Example 2 of KNN model

In [38]:
from sklearn.datasets import load_iris

In [39]:
import pandas as pd

In [70]:
import numpy as np

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
iris = load_iris()

In [42]:
x1 = iris.data

In [43]:
yr = iris.target

In [44]:
x1.shape

(150, 4)

## Split data into train and test dataset

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.2,random_state=13)

In [47]:
xtrain.shape

(120, 4)

## Initializing KNN class with euclidean equation metric with n_neighbors(k) = 3

In [56]:
from sklearn.neighbors import KNeighborsClassifier

In [57]:
knn = KNeighborsClassifier(metric = 'euclidean')

## Train KNN model

In [58]:
knn.fit(xtrain,ytrain)

KNeighborsClassifier(metric='euclidean')

In [59]:
t = xtest[0].reshape(1,-1) #Why is there a need for reshaping xtest

In [60]:
n,m = knn.kneighbors(t,n_neighbors = 5,return_distance = True)

In [61]:
m #what is m

array([[ 7, 12, 74, 21, 58]])

In [63]:
n #what is n

array([[0.3       , 0.31622777, 0.33166248, 0.37416574, 0.4       ]])

In [64]:
for i in m[0]:
    print(ytrain[i])

1
1
1
1
1


In [65]:
print(knn.predict(t))

[1]


In [66]:
print(ytest[0])

1


In [67]:
pred = knn.predict(xtest)
pred

array([1, 1, 0, 2, 2, 0, 2, 2, 0, 1, 1, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0,
       0, 2, 1, 2, 0, 2, 1, 2])

In [68]:
accuracy_score(ytest,pred) #accuracy of the KNN model on test dataset

0.9

## Indexes of missclassified samples

In [71]:
print(np.where(ytest!=pred))

(array([10, 11, 16]),)
